### ISSUE TITLE
Error in data.frame(..., check.names = FALSE)

### ISSUE THREAD

**Issue by crikkia** [vragh/seqvisr#1]
Hi,

I found your code in biostars and it is great. However, I have an issue. When I am running my dataset I often got an error message like this:

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 2940, 0

I say often because after some trying, I could visualize a dataset, then R crashed, I had to restart it and when I reopen it again, the same dataset could not be visualized anymore. The dataset you used in Biostars worked always fine. I am almost sure my fasta file is fine (at least, I can generate trees with it) . You can find it attached to the post.
Thanks for patience
Cris
[All_species_Rha_test.txt](https://github.com/vragh/seqvisr/files/6511642/All_species_Rha_test.txt)

**Comment by vragh** [comment]
HI @crikkia ,

Thank you for your interest in the package. I'm glad to see someone has found it useful!!

So I tried out the basic visualization with the MSA you've provided here, and it seems to work okay for me over multiple runs. Could you perhaps share the exact function call with me? I can check if there's something throwing the function off. I must admit I never really debugged the tool much.

Have you tried clearing your workspace and restarting the `R` session when this happens?

**Comment by crikkia** [comment]
Hello @vragh ,
Thanks for your reply. Your tool is great!
This is function I used (wioth the same dataset I sent you). Probably I messed up something.


inpmsa <- "All_species_Rha_test.txt"

msavisr(mymsa = inpmsa, myref = "my_ref", basecolors = c("Gray", "Black", "White"))

And this is the outcome
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 2940, 0

**Comment by vragh** [comment]
@crikkia ,

Thanks for sharing that code snippet with me.

I see what's going on now.

So the `myref` parameter in the function needs the name of one of the sequences in the file. This is the "reference" sequences against which all the insertions/deletions/gaps are contextualized for visualization.

**For example, in your case, you could set `myref = "SfRV"`.** So if you call the function like so:
```
library(seqvisr)

inpmsa <- "All_species_Rha_test.txt"

msavisr(mymsa = inpmsa, myref = "SfRV", basecolors = c("Gray", "Black", "White"))
```
You'd get [this](https://raw.githubusercontent.com/vragh/share/master/crikkia_example.png) as the result.

Which sequence you choose as the reference is up to you.

I apologize for letting this get confusing. I didn't bother fleshing out the documentation and examples properly since I wasn't sure there'd be any interest in the package.

**Comment by crikkia** [comment]
Dear @vragh,
Thanks a lot. Only now I noticed that I did not set myref properly. I was trying different settings, and I guess that I put myref = back to "my_ref", and I was sure that it was properly set. Sorry for bothering you with this naive error, anyway thanks again for your kindness.
Cris

**Comment by vragh** [comment]
Dear @crikkia ,

You're welcome, and it was no bother. These things tend to happen, and I'm just glad that you've managed to resolve the issue now (and can continue with your analysis)!!

I'll close this issue now, but feel free to open it again (or a new one) if something else comes up.
